In [1]:
import pandas as pd

Loading the datasets

In [2]:
customers = pd.read_csv("../Data/customers_DA[1].csv")

In [25]:
customers.head()

,customer_id,first_name,last_name,email,phone,city,state,pincode,gender,age,segment,registration_date,last_login_date,is_verified,is_active,total_orders,total_spent
0,CUST00001,Kunal,Gupta,kunal.gupta223@gmail.com,9117912889,Guwahati,Assam,314040,Male,54,New,30-07-2024,10-04-2025,0,1,7,1028341.51
1,CUST00002,Aryan,Gupta,aryan.gupta336@yahoo.in,9271550550,Navi Mumbai,Maharashtra,799535,Female,26,Budget,05-07-2023,03-05-2024,1,1,1,20337.39
2,CUST00003,Akash,Chatterjee,akash.chatterjee584@hotmail.com,9559676548,Surat,Gujarat,738196,Female,24,Regular,14-05-2022,31-10-2023,1,1,7,265688.26
3,CUST00004,Madhuri,Walia,madhuri.walia878@gmail.com,9673322422,Gwalior,Madhya Pradesh,238106,Female,23,Regular,21-01-2025,22-05-2025,1,0,7,173446.94
4,CUST00005,Vishal,Das,vishal.das342@yahoo.in,9920855521,Dhanbad,Jharkhand,783291,Female,59,Regular,06-06-2023,29-03-2024,1,0,4,239808.60

In [3]:
inventory = pd.read_csv("../Data/inventory_DA[1].csv")

In [6]:
inventory.head()

,inventory_id,product_id,warehouse_location,quantity_available,quantity_reserved,reorder_level,reorder_quantity,last_restocked_date,unit_cost,total_inventory_value,status
0,INV0001,PRD0001,Hyderabad-WH4,13,4,49,245,11-09-2023,55738,724594,Low Stock
1,INV0002,PRD0002,Kolkata-WH6,368,14,50,250,10-03-2025,48052,17683136,In Stock
2,INV0003,PRD0003,Delhi-WH2,196,19,44,220,22-11-2024,68913,13506948,In Stock
3,INV0004,PRD0004,Delhi-WH2,432,10,19,57,10-11-2024,80055,34583760,In Stock
4,INV0005,PRD0005,Bengaluru-WH3,404,16,44,88,05-08-2024,8398,3392792,In Stock

In [4]:
order_items = pd.read_csv("../Data/order_items_DA[1].csv")

In [8]:
order_items.head()

,item_id,order_id,product_id,product_name,category,quantity,unit_price,gst_rate,gst_amount,discount_amount,total_price
0,ITM0000001,ORD000001,PRD0522,HCL Cricket Bat Ultra,Sports & Fitness,1,40989,12,4918.68,7861.45,38046.23
1,ITM0000002,ORD000001,PRD0094,Berger Router Pro,Electronics,1,62532,18,11255.76,12373.11,61414.65
2,ITM0000003,ORD000001,PRD0613,Voltas Educational Toy Standard,Toys & Baby,1,1585,12,190.20,251.89,1523.31
3,ITM0000004,ORD000002,PRD0556,Ambrane Cycle Standard,Sports & Fitness,3,1107,12,398.52,631.44,3088.08
4,ITM0000005,ORD000002,PRD0026,Pebble Tablet Premium,Electronics,2,114448,18,41201.28,18707.35,251389.93

In [5]:
orders = pd.read_csv("../Data/orders_DA[1].csv")

In [10]:
orders.head()

,order_id,customer_id,order_date,order_time,status,city,state,pincode,total_amount,gst_amount,shipping_charge,discount_amount,final_amount,payment_method,shipping_partner,tracking_id,delivered_date,is_cod,channel
0,ORD000001,CUST02946,22-05-2025,17:10:00,Processing,Pune,Maharashtra,300862,100984.19,16364.64,0,20486.45,100984.19,Cash on Delivery,BlueDart,TRK354572763,NaN,1,App
1,ORD000002,CUST04232,16-10-2023,05:32:00,Delivered,Ludhiana,Punjab,387852,254478.01,41599.80,0,19338.79,254478.01,UPI,DTDC,TRK272838570,19-10-2023,0,Website
2,ORD000003,CUST08078,08-10-2023,12:32:00,Cancelled,Meerut,Uttar Pradesh,294014,32557.06,3562.92,0,696.86,32557.06,Debit Card,Amazon Logistics,TRK338505401,NaN,0,App
3,ORD000004,CUST09612,02-10-2023,08:05:00,Delivered,Nashik,Maharashtra,626047,24836.94,3092.88,0,4029.94,24836.94,UPI,DTDC,TRK289792017,09-10-2023,0,Mobile Web
4,ORD000005,CUST03065,15-06-2024,20:19:00,Delivered,Moradabad,Uttar Pradesh,409210,156689.29,25092.36,0,7805.07,156689.29,UPI,Ecom Express,TRK978240041,22-06-2024,0,App

In [6]:
payments = pd.read_csv("../Data/payments_DA[1].csv")

In [12]:
payments.head()

,payment_id,order_id,customer_id,payment_date,payment_time,payment_method,amount,status,transaction_id,bank_name,gateway,refund_amount,refund_date
0,PAY000001,ORD000001,CUST02946,22-05-2025,17:10:00,Cash on Delivery,100984.19,Success,TXN5110698474,SBI,Google Pay,0,NaN
1,PAY000002,ORD000002,CUST04232,16-10-2023,05:32:00,UPI,254478.01,Success,TXN4067460377,IndusInd,Google Pay,0,NaN
2,PAY000003,ORD000003,CUST08078,08-10-2023,12:32:00,Debit Card,32557.06,Success,TXN7056710694,Axis Bank,PhonePe,0,NaN
3,PAY000004,ORD000004,CUST09612,02-10-2023,08:05:00,UPI,24836.94,Success,TXN7460208257,Axis Bank,PhonePe,0,NaN
4,PAY000005,ORD000005,CUST03065,15-06-2024,20:19:00,UPI,156689.29,Success,TXN5835043807,PNB,Razorpay,0,NaN

In [7]:
products = pd.read_csv("../Data/products_DA[1].csv")

In [14]:
products.head()

,product_id,product_name,category,subcategory,brand,sku,mrp,selling_price,cost_price,gst_rate,hsn_code,weight_grams,supplier_id,rating,review_count,is_active,launch_date
0,PRD0001,Usha Smartphone Elite,Electronics,Smartphone,Usha,SKU-ELE-00001,92028,78958,55738,18,1144,250,SUP0198,4.3,3655,1,29-01-2025
1,PRD0002,Gizmore Smartphone Premium,Electronics,Smartphone,Gizmore,SKU-ELE-00002,91470,65917,48052,18,2857,2000,SUP0140,3.6,2321,1,17-05-2024
2,PRD0003,Fire-Boltt Smartphone Max,Electronics,Smartphone,Fire-Boltt,SKU-ELE-00003,148029,118800,68913,18,2349,250,SUP0113,3.5,4412,1,28-12-2024
3,PRD0004,Godrej Smartphone Elite,Electronics,Smartphone,Godrej,SKU-ELE-00004,152903,113203,80055,18,8130,250,SUP0068,4.5,1264,1,04-05-2023
4,PRD0005,HDFC Smartphone Elite,Electronics,Smartphone,HDFC,SKU-ELE-00005,18715,16226,8398,18,4729,1000,SUP0088,3.9,3700,1,27-11-2023

In [8]:
returns = pd.read_csv("../Data/returns_DA[1].csv")

In [16]:
returns.head()

,return_id,order_id,customer_id,return_date,reason,return_amount,refund_status,refund_date,return_condition,remarks
0,RET00001,ORD000015,CUST05470,23-12-2024,Size Issue,24167.33,Pending,30-12-2024,Damaged,Customer initiated return within 7 day window
1,RET00002,ORD000017,CUST07581,01-11-2023,Defective Product,11698.27,Refunded,06-11-2023,Damaged,Customer initiated return within 7 day window
2,RET00003,ORD000038,CUST05691,01-05-2025,Wrong Product Delivered,11147.74,Refunded,06-05-2025,Damaged,Customer initiated return within 7 day window
3,RET00004,ORD000054,CUST03170,20-06-2025,Duplicate Order,9284.55,Refunded,24-06-2025,Acceptable,Customer initiated return within 7 day window
4,RET00005,ORD000072,CUST09318,16-03-2025,Duplicate Order,36912.59,Refunded,23-03-2025,Good,Customer initiated return within 7 day window

In [9]:
suppliers = pd.read_csv("../Data/suppliers_DA[1].csv")

In [18]:
suppliers.head()

,supplier_id,supplier_name,contact_person,email,phone,city,state,pincode,category,gstin,payment_terms_days,rating,created_date,is_active
0,SUP0001,Iyer Elec Pvt Ltd,Harish Iyer,contact@iyerele.com,9362950628,Delhi,Delhi,334053,Electronics,14TRXCK1488C4Z9,15,4.1,22-05-2023,1
1,SUP0002,Sharma Offi Pvt Ltd,Mohit Sharma,contact@sharmaoff.com,9914763202,Ahmedabad,Gujarat,267414,Office Supplies,32KHFTC7224C6Z5,15,4.5,25-03-2023,1
2,SUP0003,Choudhury Beau Pvt Ltd,Nandini Choudhury,contact@choudhurybea.com,9764130526,Pune,Maharashtra,479201,Beauty & Health,28EBRUZ4814W7Z5,60,4.3,27-12-2022,1
3,SUP0004,Choudhury Fash Pvt Ltd,Vikram Choudhury,contact@choudhuryfas.com,9283758720,Chennai,Tamil Nadu,660086,Fashion,33GMHYR4598R1Z4,15,4.6,15-01-2023,1
4,SUP0005,Patil Spor Pvt Ltd,Kiran Patil,contact@patilspo.com,9636045484,Jaipur,Rajasthan,514850,Sports & Fitness,30LGGOG8019X7Z6,30,5.0,02-09-2022,1

Cleaning the datasets

In [19]:
print("Customers:",customers.shape)
print("Inventory:",inventory.shape)
print("Order_items:",order_items.shape)
print("Orders:",orders.shape)
print("Payments:",payments.shape)
print("Products:",products.shape)
print("Returns:",returns.shape)
print("Suppliers:",suppliers.shape)

Customers: (10000, 17)
Inventory: (1000, 11)
Order_items: (100000, 11)
Orders: (50000, 19)
Payments: (50000, 13)
Products: (1000, 17)
Returns: (10000, 10)
Suppliers: (200, 14)

In [20]:
# Customer table
customers.head()

,customer_id,first_name,last_name,email,phone,city,state,pincode,gender,age,segment,registration_date,last_login_date,is_verified,is_active,total_orders,total_spent
0,CUST00001,Kunal,Gupta,kunal.gupta223@gmail.com,9117912889,Guwahati,Assam,314040,Male,54,New,30-07-2024,10-04-2025,0,1,7,1028341.51
1,CUST00002,Aryan,Gupta,aryan.gupta336@yahoo.in,9271550550,Navi Mumbai,Maharashtra,799535,Female,26,Budget,05-07-2023,03-05-2024,1,1,1,20337.39
2,CUST00003,Akash,Chatterjee,akash.chatterjee584@hotmail.com,9559676548,Surat,Gujarat,738196,Female,24,Regular,14-05-2022,31-10-2023,1,1,7,265688.26
3,CUST00004,Madhuri,Walia,madhuri.walia878@gmail.com,9673322422,Gwalior,Madhya Pradesh,238106,Female,23,Regular,21-01-2025,22-05-2025,1,0,7,173446.94
4,CUST00005,Vishal,Das,vishal.das342@yahoo.in,9920855521,Dhanbad,Jharkhand,783291,Female,59,Regular,06-06-2023,29-03-2024,1,0,4,239808.60

In [26]:
customers.isnull().sum()

customer_id          0
first_name           0
last_name            0
email                0
phone                0
city                 0
state                0
pincode              0
gender               0
age                  0
segment              0
registration_date    0
last_login_date      0
is_verified          0
is_active            0
total_orders         0
total_spent          0
dtype: int64

In [27]:
customers.dtypes

customer_id              str
first_name               str
last_name                str
email                    str
phone                  int64
city                     str
state                    str
pincode                int64
gender                   str
age                    int64
segment                  str
registration_date        str
last_login_date          str
is_verified            int64
is_active              int64
total_orders           int64
total_spent          float64
dtype: object

In [28]:
customers['registration_date'] = pd.to_datetime(customers['registration_date'], format = '%d-%m-%Y')

In [29]:
customers['last_login_date'] = pd.to_datetime(customers['last_login_date'], format = '%d-%m-%Y')

In [30]:
customers.dtypes

customer_id                     str
first_name                      str
last_name                       str
email                           str
phone                         int64
city                            str
state                           str
pincode                       int64
gender                          str
age                           int64
segment                         str
registration_date    datetime64[us]
last_login_date      datetime64[us]
is_verified                   int64
is_active                     int64
total_orders                  int64
total_spent                 float64
dtype: object

In [31]:
customers.duplicated().sum()

np.int64(0)

In [34]:
customers[customers.duplicated(subset = ['customer_id'])]

Empty DataFrame
Columns: [customer_id, first_name, last_name, email, phone, city, state, pincode, gender, age, segment, registration_date, last_login_date, is_verified, is_active, total_orders, total_spent]
Index: []

In [26]:
Q1 = customers['age'].quantile(0.25)
Q3 = customers['age'].quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

age_outlier = customers[(customers['age'] < lower) | 
    (customers['age'] > upper)]

print('Q1: ',Q1)
print('Q3: ',Q3)
print('IQR: ',IQR)
print('Lower_bound: ',lower)
print('Upper_bound: ',upper)

Q1:  30.0
Q3:  54.0
IQR:  24.0
Lower_bound:  -6.0
Upper_bound:  90.0

In [63]:
len(age_outlier)

0

In [27]:
Q1 = customers['total_orders'].quantile(0.25)
Q3 = customers['total_orders'].quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

total_orders_outlier = customers[(customers['total_orders'] < lower) | 
    (customers['total_orders'] > upper)]

print('Q1: ',Q1)
print('Q3: ',Q3)
print('IQR: ',IQR)
print('Lower_bound: ',lower)
print('Upper_bound: ',upper)

Q1:  3.0
Q3:  7.0
IQR:  4.0
Lower_bound:  -3.0
Upper_bound:  13.0

In [65]:
len(total_orders_outlier)

100

In [66]:
total_orders_outlier.head(10)

,customer_id,first_name,last_name,email,phone,city,state,pincode,gender,age,segment,registration_date,last_login_date,is_verified,is_active,total_orders,total_spent
24,CUST00025,Deepak,Chopra,deepak.chopra162@hotmail.com,9593994293,Delhi,Delhi,489050,Female,62,Premium,2023-11-21,2024-11-30,1,1,15,874659.27
26,CUST00027,Vijay,Mehta,vijay.mehta986@hotmail.com,9453666583,Raipur,Chhattisgarh,336064,Male,25,Premium,2022-01-30,2025-03-17,1,1,15,1893655.96
28,CUST00029,Vishal,Banerjee,vishal.banerjee13@gmail.com,9971467813,Allahabad,Uttar Pradesh,528226,Male,44,Premium,2024-05-26,2024-08-05,1,1,14,765362.42
167,CUST00168,Priya,Dwivedi,priya.dwivedi537@gmail.com,9201197568,Srinagar,Jammu & Kashmir,203139,Female,60,Premium,2022-05-23,2022-07-24,1,1,16,1355498.12
176,CUST00177,Rohit,Tiwari,rohit.tiwari813@yahoo.in,9152624468,Howrah,West Bengal,643154,Male,35,Premium,2020-11-08,2021-07-25,1,0,14,1044598.49
189,CUST00190,Ishaan,Khanna,ishaan.khanna262@gmail.com,9785016512,Navi Mumbai,Maharashtra,488995,Female,63,Regular,2023-08-15,2023-10-17,1,1,15,390971.32
551,CUST00552,Manish,Desai,manish.desai112@gmail.com,9225155349,Moradabad,Uttar Pradesh,194926,Female,21,Premium,2022-12-14,2024-12-01,1,1,19,1664340.24
621,CUST00622,Dhruv,Patil,dhruv.patil517@gmail.com,9914163139,Rajkot,Gujarat,704569,Male,37,Premium,2021-01-21,2022-01-10,1,0,14,652987.68
1229,CUST01230,Sanjay,Patil,sanjay.patil406@gmail.com,9501761090,Madurai,Tamil Nadu,152027,Other,31,Regular,2025-05-05,2025-06-01,1,1,15,965665.25
1358,CUST01359,Sachin,Patel,sachin.patel489@gmail.com,9418984197,Bengaluru,Karnataka,745555,Male,59,Premium,2025-02-16,2025-03-28,1,1,14,608766.61

Total Orders Outlier: A few outliers were identified using the IQR method. These values were retained because they may represent genuine customers with a higher number of orders. No data correction was required.

In [28]:
Q1 = customers['total_spent'].quantile(0.25)
Q3 = customers['total_spent'].quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

total_spent_outlier = customers[(customers['total_spent'] < lower) | 
    (customers['total_spent'] > upper)]

print('Q1: ',Q1)
print('Q3: ',Q3)
print('IQR: ',IQR)
print('Lower_bound: ',lower)
print('Upper_bound: ',upper)

Q1:  88423.3725
Q3:  466058.435
IQR:  377635.0625
Lower_bound:  -478029.22125
Upper_bound:  1032511.02875

In [68]:
len(total_spent_outlier)

252

In [69]:
total_spent_outlier

,customer_id,first_name,last_name,email,phone,city,state,pincode,gender,age,segment,registration_date,last_login_date,is_verified,is_active,total_orders,total_spent
8,CUST00009,Aarav,Walia,aarav.walia768@yahoo.in,9238159208,Jodhpur,Rajasthan,336446,Male,22,Regular,2022-11-24,2025-05-18,1,1,9,1226134.82
23,CUST00024,Ankita,Choudhury,ankita.choudhury559@gmail.com,9111756387,Kolkata,West Bengal,326865,Female,55,Regular,2025-03-05,2025-03-20,1,1,8,1401970.26
26,CUST00027,Vijay,Mehta,vijay.mehta986@hotmail.com,9453666583,Raipur,Chhattisgarh,336064,Male,25,Premium,2022-01-30,2025-03-17,1,1,15,1893655.96
32,CUST00033,Akash,Desai,akash.desai753@gmail.com,9790400724,Vijayawada,Andhra Pradesh,650201,Female,52,Budget,2021-03-03,2023-05-27,0,1,5,1229860.82
99,CUST00100,Aarav,Pillai,aarav.pillai452@gmail.com,9567557361,Solapur,Maharashtra,545567,Male,30,Premium,2022-04-14,2022-07-30,1,1,12,1154137.68
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9739,CUST09740,Kartik,Chatterjee,kartik.chatterjee315@gmail.com,9812331750,Howrah,West Bengal,672719,Female,57,Premium,2022-11-30,2024-09-09,0,1,9,1758226.81
9835,CUST09836,Rakesh,Mishra,rakesh.mishra412@gmail.com,9580279105,Kolkata,West Bengal,735341,Female,36,Premium,2024-03-30,2024-07-01,1,1,7,1073038.18
9904,CUST09905,Rajan,Shah,rajan.shah960@gmail.com,9678492436,Guwahati,Assam,780277,Male,28,Regular,2024-03-31,2024-09-14,1,1,12,1095996.22
9968,CUST09969,Meera,Saxena,meera.saxena849@gmail.com,9616877230,Tiruchirappalli,Tamil Nadu,649305,Female,63,Premium,2023-10-25,2024-10-10,1,1,10,1095412.20
9972,CUST09973,Omkar,Nair,omkar.nair161@gmail.com,9994179436,Kolkata,West Bengal,211651,Female,51,Regular,2025-02-15,2025-03-08,0,1,5,1067362.79

Total Spent Outlier: Some high-value outliers were identified using the IQR method. The values appeared to represent genuine customer spending, so no changes were made.

In [28]:
# Inventory table
inventory.head()

,inventory_id,product_id,warehouse_location,quantity_available,quantity_reserved,reorder_level,reorder_quantity,last_restocked_date,unit_cost,total_inventory_value,status
0,INV0001,PRD0001,Hyderabad-WH4,13,4,49,245,11-09-2023,55738,724594,Low Stock
1,INV0002,PRD0002,Kolkata-WH6,368,14,50,250,10-03-2025,48052,17683136,In Stock
2,INV0003,PRD0003,Delhi-WH2,196,19,44,220,22-11-2024,68913,13506948,In Stock
3,INV0004,PRD0004,Delhi-WH2,432,10,19,57,10-11-2024,80055,34583760,In Stock
4,INV0005,PRD0005,Bengaluru-WH3,404,16,44,88,05-08-2024,8398,3392792,In Stock

In [70]:
inventory.isnull().sum()

inventory_id             0
product_id               0
warehouse_location       0
quantity_available       0
quantity_reserved        0
reorder_level            0
reorder_quantity         0
last_restocked_date      0
unit_cost                0
total_inventory_value    0
status                   0
dtype: int64

In [71]:
inventory.dtypes

inventory_id               str
product_id                 str
warehouse_location         str
quantity_available       int64
quantity_reserved        int64
reorder_level            int64
reorder_quantity         int64
last_restocked_date        str
unit_cost                int64
total_inventory_value    int64
status                     str
dtype: object

In [72]:
inventory['last_restocked_date'] = pd.to_datetime(inventory['last_restocked_date'], format = '%d-%m-%Y')

In [73]:
inventory.dtypes

inventory_id                        str
product_id                          str
warehouse_location                  str
quantity_available                int64
quantity_reserved                 int64
reorder_level                     int64
reorder_quantity                  int64
last_restocked_date      datetime64[us]
unit_cost                         int64
total_inventory_value             int64
status                              str
dtype: object

In [74]:
inventory.duplicated().sum()

np.int64(0)

In [29]:
Q1 = inventory['quantity_available'].quantile(0.25)
Q3 = inventory['quantity_available'].quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

quantity_available_outlier = inventory[(inventory['quantity_available'] < lower) | 
    (inventory['quantity_available'] > upper)]

print('Q1: ',Q1)
print('Q3: ',Q3)
print('IQR: ',IQR)
print('Lower_bound: ',lower)
print('Upper_bound: ',upper)

Q1:  103.5
Q3:  373.0
IQR:  269.5
Lower_bound:  -300.75
Upper_bound:  777.25

In [78]:
len(quantity_available_outlier)

0

In [30]:
Q1 = inventory['quantity_reserved'].quantile(0.25)
Q3 = inventory['quantity_reserved'].quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

quantity_reserved_outlier = inventory[(inventory['quantity_reserved'] < lower) | 
    (inventory['quantity_reserved'] > upper)]

print('Q1: ',Q1)
print('Q3: ',Q3)
print('IQR: ',IQR)
print('Lower_bound: ',lower)
print('Upper_bound: ',upper)

Q1:  4.0
Q3:  15.0
IQR:  11.0
Lower_bound:  -12.5
Upper_bound:  31.5

In [80]:
len(quantity_reserved_outlier)

0

In [31]:
Q1 = inventory['reorder_level'].quantile(0.25)
Q3 = inventory['reorder_level'].quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

reorder_level_outlier = inventory[(inventory['reorder_level'] < lower) | 
    (inventory['reorder_level'] > upper)]

print('Q1: ',Q1)
print('Q3: ',Q3)
print('IQR: ',IQR)
print('Lower_bound: ',lower)
print('Upper_bound: ',upper)

Q1:  19.0
Q3:  41.0
IQR:  22.0
Lower_bound:  -14.0
Upper_bound:  74.0

In [82]:
len(reorder_level_outlier)

0

In [32]:
Q1 = inventory['reorder_quantity'].quantile(0.25)
Q3 = inventory['reorder_quantity'].quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

reorder_quantity_outlier = inventory[(inventory['reorder_quantity'] < lower) | 
    (inventory['reorder_quantity'] > upper)]

print('Q1: ',Q1)
print('Q3: ',Q3)
print('IQR: ',IQR)
print('Lower_bound: ',lower)
print('Upper_bound: ',upper)

Q1:  60.0
Q3:  141.0
IQR:  81.0
Lower_bound:  -61.5
Upper_bound:  262.5

In [85]:
len(reorder_quantity_outlier)

0

Inventory_outliers: No statistical outliers were detected in quantity_available, quantity_reserved, reorder_level, or reorder_quantity using the IQR method. The values were within the expected range, so no changes were required.

In [33]:
Q1 = inventory['unit_cost'].quantile(0.25)
Q3 = inventory['unit_cost'].quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

unit_cost_outlier = inventory[(inventory['unit_cost'] < lower) | 
    (inventory['unit_cost'] > upper)]

print('Q1: ',Q1)
print('Q3: ',Q3)
print('IQR: ',IQR)
print('Lower_bound: ',lower)
print('Upper_bound: ',upper)

Q1:  793.5
Q3:  7054.25
IQR:  6260.75
Lower_bound:  -8597.625
Upper_bound:  16445.375

In [87]:
len(unit_cost_outlier)

129

In [95]:
unit_cost_outlier[['inventory_id', 'product_id', 'unit_cost']]

    inventory_id product_id  unit_cost
0        INV0001    PRD0001      55738
1        INV0002    PRD0002      48052
2        INV0003    PRD0003      68913
3        INV0004    PRD0004      80055
5        INV0006    PRD0006      16882
..           ...        ...        ...
591      INV0592    PRD0592      17329
593      INV0594    PRD0594      19939
595      INV0596    PRD0596      25773
596      INV0597    PRD0597      34145
599      INV0600    PRD0600      29300

[129 rows x 3 columns]

Unit Cost Outlier: A few outliers were identified in the unit_cost column using the IQR method. The values were reviewed and appeared to represent valid product costs, so no changes were made.

In [34]:
Q1 = inventory['total_inventory_value'].quantile(0.25)
Q3 = inventory['total_inventory_value'].quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

total_inventory_value_outlier = inventory[(inventory['total_inventory_value'] < lower) | 
    (inventory['total_inventory_value'] > upper)]

print('Q1: ',Q1)
print('Q3: ',Q3)
print('IQR: ',IQR)
print('Lower_bound: ',lower)
print('Upper_bound: ',upper)

Q1:  118295.0
Q3:  1610127.75
IQR:  1491832.75
Lower_bound:  -2119454.125
Upper_bound:  3847876.875

In [97]:
len(total_inventory_value_outlier)

131

In [99]:
total_inventory_value_outlier.head()

,inventory_id,product_id,warehouse_location,quantity_available,quantity_reserved,reorder_level,reorder_quantity,last_restocked_date,unit_cost,total_inventory_value,status
1,INV0002,PRD0002,Kolkata-WH6,368,14,50,250,2025-03-10,48052,17683136,In Stock
2,INV0003,PRD0003,Delhi-WH2,196,19,44,220,2024-11-22,68913,13506948,In Stock
3,INV0004,PRD0004,Delhi-WH2,432,10,19,57,2024-11-10,80055,34583760,In Stock
5,INV0006,PRD0006,Delhi-WH2,349,11,50,100,2025-06-05,16882,5891818,In Stock
8,INV0009,PRD0009,Bengaluru-WH3,398,8,31,124,2023-12-27,34418,13698364,In Stock

Total Inventory Value Outlier: Some statistical outliers were identified in the total_inventory_value column using the IQR method. The values were reviewed and appeared to be valid inventory values based on the quantity and unit cost. Therefore, no changes were made.

In [38]:
# Order_items table
order_items.head()

,item_id,order_id,product_id,product_name,category,quantity,unit_price,gst_rate,gst_amount,discount_amount,total_price
0,ITM0000001,ORD000001,PRD0522,HCL Cricket Bat Ultra,Sports & Fitness,1,40989,12,4918.68,7861.45,38046.23
1,ITM0000002,ORD000001,PRD0094,Berger Router Pro,Electronics,1,62532,18,11255.76,12373.11,61414.65
2,ITM0000003,ORD000001,PRD0613,Voltas Educational Toy Standard,Toys & Baby,1,1585,12,190.20,251.89,1523.31
3,ITM0000004,ORD000002,PRD0556,Ambrane Cycle Standard,Sports & Fitness,3,1107,12,398.52,631.44,3088.08
4,ITM0000005,ORD000002,PRD0026,Pebble Tablet Premium,Electronics,2,114448,18,41201.28,18707.35,251389.93

In [11]:
order_items.isnull().sum()

item_id            0
order_id           0
product_id         0
product_name       0
category           0
quantity           0
unit_price         0
gst_rate           0
gst_amount         0
discount_amount    0
total_price        0
dtype: int64

In [12]:
order_items.dtypes

item_id                str
order_id               str
product_id             str
product_name           str
category               str
quantity             int64
unit_price           int64
gst_rate             int64
gst_amount         float64
discount_amount    float64
total_price        float64
dtype: object

In [35]:
Q1 = order_items['quantity'].quantile(0.25)
Q3 = order_items['quantity'].quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

order_items_quantity_outlier = order_items[(order_items['quantity'] < lower) | 
    (order_items['quantity'] > upper)]

print('Q1: ',Q1)
print('Q3: ',Q3)
print('IQR: ',IQR)
print('Lower_bound: ',lower)
print('Upper_bound: ',upper)

Q1:  1.0
Q3:  3.0
IQR:  2.0
Lower_bound:  -2.0
Upper_bound:  6.0

In [18]:
len(order_items_quantity_outlier)

0

In [24]:
Q1 = order_items['unit_price'].quantile(0.25)
Q3 = order_items['unit_price'].quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

order_items_unit_price_outlier = order_items[(order_items['unit_price'] < lower) | 
    (order_items['unit_price'] > upper)]

print('Q1: ',Q1)
print('Q3: ',Q3)
print('IQR: ',IQR)
print('Lower_bound: ',lower)
print('Upper_bound: ',upper)

Q1:  1263.0
Q3:  11526.0
IQR:  10263.0
Lower_bound:  -14131.5
Upper_bound:  26920.5

In [25]:
len(order_items_unit_price_outlier)

12589

In [23]:
order_items_unit_price_outlier.head()

,item_id,order_id,product_id,product_name,category,quantity,unit_price,gst_rate,gst_amount,discount_amount,total_price
0,ITM0000001,ORD000001,PRD0522,HCL Cricket Bat Ultra,Sports & Fitness,1,40989,12,4918.68,7861.45,38046.23
1,ITM0000002,ORD000001,PRD0094,Berger Router Pro,Electronics,1,62532,18,11255.76,12373.11,61414.65
4,ITM0000005,ORD000002,PRD0026,Pebble Tablet Premium,Electronics,2,114448,18,41201.28,18707.35,251389.93
8,ITM0000009,ORD000005,PRD0022,ITC Tablet Base,Electronics,2,69701,18,25092.36,7805.07,156689.29
11,ITM0000012,ORD000007,PRD0046,Pidilite Headphones Premium,Electronics,2,149361,18,53769.96,50097.11,302394.85

Unit_price_outlier: The IQR method identified 12,589 potential outliers in the Unit Price column. These values were reviewed and retained because the high prices may represent legitimate product prices rather than data-entry errors. No modification was applied.

In [36]:
Q1 = order_items['gst_amount'].quantile(0.25)
Q3 = order_items['gst_amount'].quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

order_items_gst_amount_outlier = order_items[(order_items['gst_amount'] < lower) | 
    (order_items['gst_amount'] > upper)]

print('Q1: ',Q1)
print('Q3: ',Q3)
print('IQR: ',IQR)
print('Lower_bound: ',lower)
print('Upper_bound: ',upper)

Q1:  150.975
Q3:  3068.16
IQR:  2917.185
Lower_bound:  -4224.8025
Upper_bound:  7443.9375

In [37]:
len(order_items_gst_amount_outlier)

12577

In [39]:
order_items_gst_amount_outlier.head(10)

,item_id,order_id,product_id,product_name,category,quantity,unit_price,gst_rate,gst_amount,discount_amount,total_price
1,ITM0000002,ORD000001,PRD0094,Berger Router Pro,Electronics,1,62532,18,11255.76,12373.11,61414.65
4,ITM0000005,ORD000002,PRD0026,Pebble Tablet Premium,Electronics,2,114448,18,41201.28,18707.35,251389.93
8,ITM0000009,ORD000005,PRD0022,ITC Tablet Base,Electronics,2,69701,18,25092.36,7805.07,156689.29
11,ITM0000012,ORD000007,PRD0046,Pidilite Headphones Premium,Electronics,2,149361,18,53769.96,50097.11,302394.85
14,ITM0000015,ORD000008,PRD0017,Pidilite Laptop Elite,Electronics,1,98845,18,17792.10,16468.22,100168.88
20,ITM0000021,ORD000009,PRD0858,Hindusta Unilever Car Seat Cover Pro,Automotive,3,8942,28,7511.28,4480.55,29856.73
34,ITM0000035,ORD000014,PRD0596,Voltas Resistance Band Pro,Sports & Fitness,2,45453,12,10908.72,3041.81,98772.91
39,ITM0000040,ORD000016,PRD0016,ITC Laptop Lite,Electronics,1,136777,18,24619.86,302.04,161094.82
49,ITM0000050,ORD000021,PRD0504,Orient Yoga Mat Ultra,Sports & Fitness,3,48271,12,17377.56,22502.26,139688.30
50,ITM0000051,ORD000021,PRD0057,Orient Bluetooth Speaker Max,Electronics,2,59826,18,21537.36,16642.61,124546.75

GST_Amount_Outlier: The IQR method identified potential outliers in the GST Amount column. These values were reviewed and retained because higher GST amounts are associated with high-value products and do not necessarily indicate data-quality issues.

In [40]:
Q1 = order_items['discount_amount'].quantile(0.25)
Q3 = order_items['discount_amount'].quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

order_items_discount_amount_outlier = order_items[(order_items['discount_amount'] < lower) | 
    (order_items['discount_amount'] > upper)]

print('Q1: ',Q1)
print('Q3: ',Q3)
print('IQR: ',IQR)
print('Lower_bound: ',lower)
print('Upper_bound: ',upper)

Q1:  150.11
Q3:  1948.9025000000001
IQR:  1798.7925
Lower_bound:  -2548.07875
Upper_bound:  4647.09125

In [42]:
len(order_items_discount_amount_outlier)

13185

In [44]:
order_items_discount_amount_outlier.head()

,item_id,order_id,product_id,product_name,category,quantity,unit_price,gst_rate,gst_amount,discount_amount,total_price
0,ITM0000001,ORD000001,PRD0522,HCL Cricket Bat Ultra,Sports & Fitness,1,40989,12,4918.68,7861.45,38046.23
1,ITM0000002,ORD000001,PRD0094,Berger Router Pro,Electronics,1,62532,18,11255.76,12373.11,61414.65
4,ITM0000005,ORD000002,PRD0026,Pebble Tablet Premium,Electronics,2,114448,18,41201.28,18707.35,251389.93
8,ITM0000009,ORD000005,PRD0022,ITC Tablet Base,Electronics,2,69701,18,25092.36,7805.07,156689.29
11,ITM0000012,ORD000007,PRD0046,Pidilite Headphones Premium,Electronics,2,149361,18,53769.96,50097.11,302394.85

Discount_Amount_Outlier: The IQR method identified 13,185 potential outliers. These values were reviewed and retained because higher discount amounts can occur naturally for higher-priced products. No modification was applied.

In [49]:
Q1 = order_items['total_price'].quantile(0.25)
Q3 = order_items['total_price'].quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

order_items_total_price_outlier = order_items[(order_items['total_price'] < lower) | 
    (order_items['total_price'] > upper)]

print('Q1: ',Q1)
print('Q3: ',Q3)
print('IQR: ',IQR)
print('Lower_bound: ',lower)
print('Upper_bound: ',upper)

Q1:  2177.455
Q3:  22940.45
IQR:  20762.995000000003
Lower_bound:  -28967.037500000006
Upper_bound:  54084.942500000005

In [50]:
len(order_items_total_price_outlier)

12688

In [51]:
order_items_total_price_outlier.head()

,item_id,order_id,product_id,product_name,category,quantity,unit_price,gst_rate,gst_amount,discount_amount,total_price
1,ITM0000002,ORD000001,PRD0094,Berger Router Pro,Electronics,1,62532,18,11255.76,12373.11,61414.65
4,ITM0000005,ORD000002,PRD0026,Pebble Tablet Premium,Electronics,2,114448,18,41201.28,18707.35,251389.93
8,ITM0000009,ORD000005,PRD0022,ITC Tablet Base,Electronics,2,69701,18,25092.36,7805.07,156689.29
11,ITM0000012,ORD000007,PRD0046,Pidilite Headphones Premium,Electronics,2,149361,18,53769.96,50097.11,302394.85
14,ITM0000015,ORD000008,PRD0017,Pidilite Laptop Elite,Electronics,1,98845,18,17792.10,16468.22,100168.88

Total_Price_Outlier: The IQR method identified 12,688 potential outliers, with an upper bound of 54084. These values were reviewed in relation to other order-item variables such as Unit Price, Quantity, GST Amount, and Discount Amount. Higher Total Price values can occur naturally for higher-priced products and larger quantities. Therefore, the flagged values were retained and no modification was applied.

In [52]:
order_items.duplicated().sum()

np.int64(0)

In [47]:
# Orders table
orders.head()

,order_id,customer_id,order_date,order_time,status,city,state,pincode,total_amount,gst_amount,shipping_charge,discount_amount,final_amount,payment_method,shipping_partner,tracking_id,delivered_date,is_cod,channel
0,ORD000001,CUST02946,22-05-2025,17:10:00,Processing,Pune,Maharashtra,300862,100984.19,16364.64,0,20486.45,100984.19,Cash on Delivery,BlueDart,TRK354572763,NaN,1,App
1,ORD000002,CUST04232,16-10-2023,05:32:00,Delivered,Ludhiana,Punjab,387852,254478.01,41599.80,0,19338.79,254478.01,UPI,DTDC,TRK272838570,19-10-2023,0,Website
2,ORD000003,CUST08078,08-10-2023,12:32:00,Cancelled,Meerut,Uttar Pradesh,294014,32557.06,3562.92,0,696.86,32557.06,Debit Card,Amazon Logistics,TRK338505401,NaN,0,App
3,ORD000004,CUST09612,02-10-2023,08:05:00,Delivered,Nashik,Maharashtra,626047,24836.94,3092.88,0,4029.94,24836.94,UPI,DTDC,TRK289792017,09-10-2023,0,Mobile Web
4,ORD000005,CUST03065,15-06-2024,20:19:00,Delivered,Moradabad,Uttar Pradesh,409210,156689.29,25092.36,0,7805.07,156689.29,UPI,Ecom Express,TRK978240041,22-06-2024,0,App

In [54]:
orders.isnull().sum()

order_id                0
customer_id             0
order_date              0
order_time              0
status                  0
city                    0
state                   0
pincode                 0
total_amount            0
gst_amount              0
shipping_charge         0
discount_amount         0
final_amount            0
payment_method          0
shipping_partner        0
tracking_id             0
delivered_date      17501
is_cod                  0
channel                 0
dtype: int64

In [55]:
orders[orders['delivered_date'].isnull()]['status'].value_counts()

status
Cancelled     5996
Shipped       5071
Returned      3933
Processing    2501
Name: count, dtype: int64

Finding: The delivered_date column contains 17,501 missing values. These records belong to Cancelled, Shipped, Returned, and Processing orders. Since these orders do not have a completed delivery status, the missing delivery dates are considered valid and were retained as null. No imputation or row deletion was performed.

In [56]:
orders.dtypes

order_id                str
customer_id             str
order_date              str
order_time              str
status                  str
city                    str
state                   str
pincode               int64
total_amount        float64
gst_amount          float64
shipping_charge       int64
discount_amount     float64
final_amount        float64
payment_method          str
shipping_partner        str
tracking_id             str
delivered_date          str
is_cod                int64
channel                 str
dtype: object

In [57]:
orders['order_date'] = pd.to_datetime(orders['order_date'], format = '%d-%m-%Y')

In [58]:
orders['order_time'] = pd.to_datetime(orders['order_time'], format = '%H:%M:%S').dt.time

In [59]:
orders['delivered_date'] = pd.to_datetime(orders['delivered_date'], format = '%d-%m-%Y')

In [73]:
orders.dtypes

order_id                       str
customer_id                    str
order_date          datetime64[us]
order_time                  object
status                         str
city                           str
state                          str
pincode                      int64
total_amount               float64
gst_amount                 float64
shipping_charge              int64
discount_amount            float64
final_amount               float64
payment_method                 str
shipping_partner               str
tracking_id                    str
delivered_date      datetime64[us]
is_cod                       int64
channel                        str
dtype: object

In [60]:
orders.duplicated().sum()

np.int64(0)

In [62]:
orders.duplicated(subset = ['order_id']).sum()

np.int64(0)

In [63]:
Q1 = orders['total_amount'].quantile(0.25)
Q3 = orders['total_amount'].quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

orders_total_amount_outlier = orders[(orders['total_amount'] < lower) | 
    (orders['total_amount'] > upper)]

print('Q1: ',Q1)
print('Q3: ',Q3)
print('IQR: ',IQR)
print('Lower_bound: ',lower)
print('Upper_bound: ',upper)

Q1:  6893.5199999999995
Q3:  71495.74
IQR:  64602.22000000001
Lower_bound:  -90009.81000000001
Upper_bound:  168399.07

In [64]:
len(orders_total_amount_outlier)

5243

In [65]:
orders_total_amount_outlier.head()

,order_id,customer_id,order_date,order_time,status,city,state,pincode,total_amount,gst_amount,shipping_charge,discount_amount,final_amount,payment_method,shipping_partner,tracking_id,delivered_date,is_cod,channel
1,ORD000002,CUST04232,2023-10-16,05:32:00,Delivered,Ludhiana,Punjab,387852,254478.01,41599.80,0,19338.79,254478.01,UPI,DTDC,TRK272838570,2023-10-19,0,Website
6,ORD000007,CUST00754,2025-04-12,03:48:00,Shipped,Lucknow,Uttar Pradesh,679970,306195.59,53769.96,0,50543.37,306195.59,Debit Card,DTDC,TRK157558824,NaT,0,App
20,ORD000021,CUST09929,2024-08-23,20:04:00,Delivered,Madurai,Tamil Nadu,217812,264235.05,38914.92,0,39144.87,264235.05,EMI,Shadowfax,TRK817403430,2024-08-25,0,Website
29,ORD000030,CUST08488,2025-04-18,16:05:00,Delivered,Pune,Maharashtra,772225,239257.70,43271.82,0,44413.12,239257.70,Net Banking,Amazon Logistics,TRK753111316,2025-04-21,0,App
32,ORD000033,CUST08912,2025-04-01,06:30:00,Delivered,Gwalior,Madhya Pradesh,330143,339041.77,53891.66,0,57865.89,339041.77,UPI,Shadowfax,TRK955888595,2025-04-07,0,Website

Total Amount Outlier: The IQR method identified 5,243 potential outliers, with an upper bound of ₹168,399.07. These values were reviewed and retained because higher total amounts can represent legitimate high-value orders. No modification was applied.

In [66]:
Q1 = orders['gst_amount'].quantile(0.25)
Q3 = orders['gst_amount'].quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

orders_gst_amount_outlier = orders[(orders['gst_amount'] < lower) | 
    (orders['gst_amount'] > upper)]

print('Q1: ',Q1)
print('Q3: ',Q3)
print('IQR: ',IQR)
print('Lower_bound: ',lower)
print('Upper_bound: ',upper)

Q1:  787.5
Q3:  9381.880000000001
IQR:  8594.380000000001
Lower_bound:  -12104.070000000002
Upper_bound:  22273.450000000004

In [67]:
len(orders_gst_amount_outlier)

6121

In [68]:
orders_gst_amount_outlier.head()

,order_id,customer_id,order_date,order_time,status,city,state,pincode,total_amount,gst_amount,shipping_charge,discount_amount,final_amount,payment_method,shipping_partner,tracking_id,delivered_date,is_cod,channel
1,ORD000002,CUST04232,2023-10-16,05:32:00,Delivered,Ludhiana,Punjab,387852,254478.01,41599.80,0,19338.79,254478.01,UPI,DTDC,TRK272838570,2023-10-19,0,Website
4,ORD000005,CUST03065,2024-06-15,20:19:00,Delivered,Moradabad,Uttar Pradesh,409210,156689.29,25092.36,0,7805.07,156689.29,UPI,Ecom Express,TRK978240041,2024-06-22,0,App
6,ORD000007,CUST00754,2025-04-12,03:48:00,Shipped,Lucknow,Uttar Pradesh,679970,306195.59,53769.96,0,50543.37,306195.59,Debit Card,DTDC,TRK157558824,NaT,0,App
15,ORD000016,CUST08893,2024-06-30,23:09:00,Processing,Firozabad,Uttar Pradesh,687974,163045.34,24959.16,0,575.82,163045.34,UPI,BlueDart,TRK840846841,NaT,0,App
20,ORD000021,CUST09929,2024-08-23,20:04:00,Delivered,Madurai,Tamil Nadu,217812,264235.05,38914.92,0,39144.87,264235.05,EMI,Shadowfax,TRK817403430,2024-08-25,0,Website

GST Amount: The IQR method identified 6121 potential outliers, with an upper bound of ₹22,273. These values were reviewed and retained because higher GST amounts can occur naturally for high-value orders. No modification was applied.

In [70]:
Q1 = orders['shipping_charge'].quantile(0.25)
Q3 = orders['shipping_charge'].quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

orders_shipping_charge_outlier = orders[(orders['shipping_charge'] < lower) | 
    (orders['shipping_charge'] > upper)]

print('Q1: ',Q1)
print('Q3: ',Q3)
print('IQR: ',IQR)
print('Lower_bound: ',lower)
print('Upper_bound: ',upper)

Q1:  0.0
Q3:  0.0
IQR:  0.0
Lower_bound:  0.0
Upper_bound:  0.0

In [71]:
len(orders_shipping_charge_outlier)

894

In [72]:
orders_shipping_charge_outlier.head()

,order_id,customer_id,order_date,order_time,status,city,state,pincode,total_amount,gst_amount,shipping_charge,discount_amount,final_amount,payment_method,shipping_partner,tracking_id,delivered_date,is_cod,channel
173,ORD000174,CUST01495,2024-05-14,19:01:00,Returned,Jodhpur,Rajasthan,366904,241.98,38.88,40,12.90,281.98,Credit Card,DTDC,TRK715941452,NaT,0,Website
586,ORD000587,CUST02363,2024-06-15,17:31:00,Delivered,Lucknow,Uttar Pradesh,233888,457.35,0.00,59,56.65,516.35,Wallet,BlueDart,TRK753628561,2024-06-22,0,Website
665,ORD000666,CUST09807,2023-10-13,13:10:00,Delivered,Jodhpur,Rajasthan,634966,389.84,0.00,59,53.16,448.84,Debit Card,Ecom Express,TRK662952612,2023-10-16,0,App
780,ORD000781,CUST06217,2023-07-23,03:52:00,Delivered,Jodhpur,Rajasthan,683562,293.11,0.00,40,42.89,333.11,UPI,XpressBees,TRK759206347,2023-07-27,0,App
841,ORD000842,CUST05381,2023-07-01,23:35:00,Delivered,Faridabad,Haryana,324536,405.11,20.85,59,32.74,464.11,Debit Card,Ecom Express,TRK424591839,2023-07-05,0,App

Shipping Charge Outlier: The IQR method identified 894 potential outliers, with a lower bound of ₹0 and an upper bound of ₹0. The flagged values include legitimate shipping charges such as ₹40 and ₹59. Since these values represent valid shipping charges rather than data-entry errors, they were retained and no modification was applied.

In [73]:
Q1 = orders['discount_amount'].quantile(0.25)
Q3 = orders['discount_amount'].quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

orders_discount_amount_outlier = orders[(orders['discount_amount'] < lower) | 
    (orders['discount_amount'] > upper)]

print('Q1: ',Q1)
print('Q3: ',Q3)
print('IQR: ',IQR)
print('Lower_bound: ',lower)
print('Upper_bound: ',upper)

Q1:  781.0325
Q3:  7370.285
IQR:  6589.2525
Lower_bound:  -9102.84625
Upper_bound:  17254.16375

In [74]:
len(orders_discount_amount_outlier)

5429

In [75]:
orders_discount_amount_outlier.head()

,order_id,customer_id,order_date,order_time,status,city,state,pincode,total_amount,gst_amount,shipping_charge,discount_amount,final_amount,payment_method,shipping_partner,tracking_id,delivered_date,is_cod,channel
0,ORD000001,CUST02946,2025-05-22,17:10:00,Processing,Pune,Maharashtra,300862,100984.19,16364.64,0,20486.45,100984.19,Cash on Delivery,BlueDart,TRK354572763,NaT,1,App
1,ORD000002,CUST04232,2023-10-16,05:32:00,Delivered,Ludhiana,Punjab,387852,254478.01,41599.80,0,19338.79,254478.01,UPI,DTDC,TRK272838570,2023-10-19,0,Website
6,ORD000007,CUST00754,2025-04-12,03:48:00,Shipped,Lucknow,Uttar Pradesh,679970,306195.59,53769.96,0,50543.37,306195.59,Debit Card,DTDC,TRK157558824,NaT,0,App
20,ORD000021,CUST09929,2024-08-23,20:04:00,Delivered,Madurai,Tamil Nadu,217812,264235.05,38914.92,0,39144.87,264235.05,EMI,Shadowfax,TRK817403430,2024-08-25,0,Website
29,ORD000030,CUST08488,2025-04-18,16:05:00,Delivered,Pune,Maharashtra,772225,239257.70,43271.82,0,44413.12,239257.70,Net Banking,Amazon Logistics,TRK753111316,2025-04-21,0,App

Discount Amount Outlier: The IQR method identified 5,429 potential outliers, with a lower bound of −₹9,102 and an upper bound of ₹17,254. These values were reviewed and retained because higher discount amounts can occur legitimately for high-value orders or larger discounts. No modification was applied.

In [77]:
Q1 = orders['final_amount'].quantile(0.25)
Q3 = orders['final_amount'].quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

orders_final_amount_outlier = orders[(orders['final_amount'] < lower) | 
    (orders['final_amount'] > upper)]

print('Q1: ',Q1)
print('Q3: ',Q3)
print('IQR: ',IQR)
print('Lower_bound: ',lower)
print('Upper_bound: ',upper)

Q1:  6893.5199999999995
Q3:  71495.74
IQR:  64602.22000000001
Lower_bound:  -90009.81000000001
Upper_bound:  168399.07

In [78]:
len(orders_final_amount_outlier)

5243

In [79]:
orders_final_amount_outlier.head()

,order_id,customer_id,order_date,order_time,status,city,state,pincode,total_amount,gst_amount,shipping_charge,discount_amount,final_amount,payment_method,shipping_partner,tracking_id,delivered_date,is_cod,channel
1,ORD000002,CUST04232,2023-10-16,05:32:00,Delivered,Ludhiana,Punjab,387852,254478.01,41599.80,0,19338.79,254478.01,UPI,DTDC,TRK272838570,2023-10-19,0,Website
6,ORD000007,CUST00754,2025-04-12,03:48:00,Shipped,Lucknow,Uttar Pradesh,679970,306195.59,53769.96,0,50543.37,306195.59,Debit Card,DTDC,TRK157558824,NaT,0,App
20,ORD000021,CUST09929,2024-08-23,20:04:00,Delivered,Madurai,Tamil Nadu,217812,264235.05,38914.92,0,39144.87,264235.05,EMI,Shadowfax,TRK817403430,2024-08-25,0,Website
29,ORD000030,CUST08488,2025-04-18,16:05:00,Delivered,Pune,Maharashtra,772225,239257.70,43271.82,0,44413.12,239257.70,Net Banking,Amazon Logistics,TRK753111316,2025-04-21,0,App
32,ORD000033,CUST08912,2025-04-01,06:30:00,Delivered,Gwalior,Madhya Pradesh,330143,339041.77,53891.66,0,57865.89,339041.77,UPI,Shadowfax,TRK955888595,2025-04-07,0,Website

Final Amount: The IQR method identified 5,243 potential outliers, with an upper bound of ₹168,399. These values were reviewed and retained because higher final amounts can occur naturally for high-value orders. No modification was applied.

In [61]:
# Payments table
payments.head()

,payment_id,order_id,customer_id,payment_date,payment_time,payment_method,amount,status,transaction_id,bank_name,gateway,refund_amount,refund_date
0,PAY000001,ORD000001,CUST02946,22-05-2025,17:10:00,Cash on Delivery,100984.19,Success,TXN5110698474,SBI,Google Pay,0,NaN
1,PAY000002,ORD000002,CUST04232,16-10-2023,05:32:00,UPI,254478.01,Success,TXN4067460377,IndusInd,Google Pay,0,NaN
2,PAY000003,ORD000003,CUST08078,08-10-2023,12:32:00,Debit Card,32557.06,Success,TXN7056710694,Axis Bank,PhonePe,0,NaN
3,PAY000004,ORD000004,CUST09612,02-10-2023,08:05:00,UPI,24836.94,Success,TXN7460208257,Axis Bank,PhonePe,0,NaN
4,PAY000005,ORD000005,CUST03065,15-06-2024,20:19:00,UPI,156689.29,Success,TXN5835043807,PNB,Razorpay,0,NaN

In [80]:
payments.isnull().sum()

payment_id            0
order_id              0
customer_id           0
payment_date          0
payment_time          0
payment_method        0
amount                0
status                0
transaction_id        0
bank_name             0
gateway               0
refund_amount         0
refund_date       50000
dtype: int64

In [81]:
payments[payments['refund_date'].isnull()]['status'].value_counts()

status
Success    48252
Failed      1748
Name: count, dtype: int64

In [85]:
payments['refund_amount'].value_counts(dropna=False)

refund_amount
0    50000
Name: count, dtype: int64

Refund Date: The refund_date column contains 50,000 missing values. The corresponding refund_amount is 0 for all records, indicating that no refunds were recorded. Therefore, the missing refund dates are considered expected missing values and were retained as null. No imputation or row deletion was performed.

In [82]:
payments.dtypes

payment_id            str
order_id              str
customer_id           str
payment_date          str
payment_time          str
payment_method        str
amount            float64
status                str
transaction_id        str
bank_name             str
gateway               str
refund_amount       int64
refund_date       float64
dtype: object

In [46]:
payments['payment_date'] = pd.to_datetime(payments['payment_date'], format = '%d-%m-%Y')

In [47]:
payments['payment_time'] = pd.to_datetime(payments['payment_time'], format = '%H:%M:%S')

In [48]:
payments['refund_date'] = pd.to_datetime(payments['refund_date'], format = '%d-%m-%Y')

In [49]:
payments.dtypes

payment_id                   str
order_id                     str
customer_id                  str
payment_date      datetime64[us]
payment_time      datetime64[us]
payment_method               str
amount                   float64
status                       str
transaction_id               str
bank_name                    str
gateway                      str
refund_amount              int64
refund_date        datetime64[s]
dtype: object

In [83]:
payments.duplicated().sum()

np.int64(0)

In [89]:
orders['final_amount'].equals(payments['amount'])

True

Amount: The amount column contains the same values as the Orders final_amount column. Therefore, the outlier analysis was already performed on the corresponding values in the Orders table, and the analysis was not repeated.

In [74]:
# Products table
products.head()

,product_id,product_name,category,subcategory,brand,sku,mrp,selling_price,cost_price,gst_rate,hsn_code,weight_grams,supplier_id,rating,review_count,is_active,launch_date
0,PRD0001,Usha Smartphone Elite,Electronics,Smartphone,Usha,SKU-ELE-00001,92028,78958,55738,18,1144,250,SUP0198,4.3,3655,1,29-01-2025
1,PRD0002,Gizmore Smartphone Premium,Electronics,Smartphone,Gizmore,SKU-ELE-00002,91470,65917,48052,18,2857,2000,SUP0140,3.6,2321,1,17-05-2024
2,PRD0003,Fire-Boltt Smartphone Max,Electronics,Smartphone,Fire-Boltt,SKU-ELE-00003,148029,118800,68913,18,2349,250,SUP0113,3.5,4412,1,28-12-2024
3,PRD0004,Godrej Smartphone Elite,Electronics,Smartphone,Godrej,SKU-ELE-00004,152903,113203,80055,18,8130,250,SUP0068,4.5,1264,1,04-05-2023
4,PRD0005,HDFC Smartphone Elite,Electronics,Smartphone,HDFC,SKU-ELE-00005,18715,16226,8398,18,4729,1000,SUP0088,3.9,3700,1,27-11-2023

In [90]:
products.isnull().sum()

product_id       0
product_name     0
category         0
subcategory      0
brand            0
sku              0
mrp              0
selling_price    0
cost_price       0
gst_rate         0
hsn_code         0
weight_grams     0
supplier_id      0
rating           0
review_count     0
is_active        0
launch_date      0
dtype: int64

In [91]:
products.dtypes

product_id           str
product_name         str
category             str
subcategory          str
brand                str
sku                  str
mrp                int64
selling_price      int64
cost_price         int64
gst_rate           int64
hsn_code           int64
weight_grams       int64
supplier_id          str
rating           float64
review_count       int64
is_active          int64
launch_date          str
dtype: object

In [92]:
products['launch_date'] = pd.to_datetime(products['launch_date'], format = '%d-%m-%Y')

In [93]:
products.dtypes

product_id                  str
product_name                str
category                    str
subcategory                 str
brand                       str
sku                         str
mrp                       int64
selling_price             int64
cost_price                int64
gst_rate                  int64
hsn_code                  int64
weight_grams              int64
supplier_id                 str
rating                  float64
review_count              int64
is_active                 int64
launch_date      datetime64[us]
dtype: object

In [94]:
products.duplicated().sum()

np.int64(0)

In [95]:
Q1 = products['mrp'].quantile(0.25)
Q3 = products['mrp'].quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

products_mrp_outlier = products[(products['mrp'] < lower) | 
    (products['mrp'] > upper)]

print('Q1: ',Q1)
print('Q3: ',Q3)
print('IQR: ',IQR)
print('Lower_bound: ',lower)
print('Upper_bound: ',upper)

Q1:  1549.75
Q3:  14192.5
IQR:  12642.75
Lower_bound:  -17414.375
Upper_bound:  33156.625

In [96]:
len(products_mrp_outlier)

129

In [97]:
products_mrp_outlier.head()

,product_id,product_name,category,subcategory,brand,sku,mrp,selling_price,cost_price,gst_rate,hsn_code,weight_grams,supplier_id,rating,review_count,is_active,launch_date
0,PRD0001,Usha Smartphone Elite,Electronics,Smartphone,Usha,SKU-ELE-00001,92028,78958,55738,18,1144,250,SUP0198,4.3,3655,1,2025-01-29
1,PRD0002,Gizmore Smartphone Premium,Electronics,Smartphone,Gizmore,SKU-ELE-00002,91470,65917,48052,18,2857,2000,SUP0140,3.6,2321,1,2024-05-17
2,PRD0003,Fire-Boltt Smartphone Max,Electronics,Smartphone,Fire-Boltt,SKU-ELE-00003,148029,118800,68913,18,2349,250,SUP0113,3.5,4412,1,2024-12-28
3,PRD0004,Godrej Smartphone Elite,Electronics,Smartphone,Godrej,SKU-ELE-00004,152903,113203,80055,18,8130,250,SUP0068,4.5,1264,1,2023-05-04
5,PRD0006,Orient Smartphone Base,Electronics,Smartphone,Orient,SKU-ELE-00006,41611,33013,16882,18,2189,1500,SUP0029,4.8,874,1,2025-04-28

MRP Outlier: The IQR method identified 129 potential outliers, with an upper bound of ₹33,156. These values were reviewed and retained because higher MRP values can represent legitimate high-priced products rather than data-entry errors. No modification was applied.

In [98]:
Q1 = products['selling_price'].quantile(0.25)
Q3 = products['selling_price'].quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

products_selling_price_outlier = products[(products['selling_price'] < lower) | 
    (products['selling_price'] > upper)]

print('Q1: ',Q1)
print('Q3: ',Q3)
print('IQR: ',IQR)
print('Lower_bound: ',lower)
print('Upper_bound: ',upper)

Q1:  1255.25
Q3:  11347.25
IQR:  10092.0
Lower_bound:  -13882.75
Upper_bound:  26485.25

In [99]:
len(products_selling_price_outlier)

127

In [100]:
products_selling_price_outlier.head()

,product_id,product_name,category,subcategory,brand,sku,mrp,selling_price,cost_price,gst_rate,hsn_code,weight_grams,supplier_id,rating,review_count,is_active,launch_date
0,PRD0001,Usha Smartphone Elite,Electronics,Smartphone,Usha,SKU-ELE-00001,92028,78958,55738,18,1144,250,SUP0198,4.3,3655,1,2025-01-29
1,PRD0002,Gizmore Smartphone Premium,Electronics,Smartphone,Gizmore,SKU-ELE-00002,91470,65917,48052,18,2857,2000,SUP0140,3.6,2321,1,2024-05-17
2,PRD0003,Fire-Boltt Smartphone Max,Electronics,Smartphone,Fire-Boltt,SKU-ELE-00003,148029,118800,68913,18,2349,250,SUP0113,3.5,4412,1,2024-12-28
3,PRD0004,Godrej Smartphone Elite,Electronics,Smartphone,Godrej,SKU-ELE-00004,152903,113203,80055,18,8130,250,SUP0068,4.5,1264,1,2023-05-04
5,PRD0006,Orient Smartphone Base,Electronics,Smartphone,Orient,SKU-ELE-00006,41611,33013,16882,18,2189,1500,SUP0029,4.8,874,1,2025-04-28

Selling Price: The IQR method identified 127 potential outliers, with an upper bound of 26,485. These values were reviewed and retained because higher selling prices can represent legitimate high-priced products rather than data-entry errors. No modification was applied.

In [101]:
Q1 = products['cost_price'].quantile(0.25)
Q3 = products['cost_price'].quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

products_cost_price_outlier = products[(products['cost_price'] < lower) | 
    (products['cost_price'] > upper)]

print('Q1: ',Q1)
print('Q3: ',Q3)
print('IQR: ',IQR)
print('Lower_bound: ',lower)
print('Upper_bound: ',upper)

Q1:  793.5
Q3:  7054.25
IQR:  6260.75
Lower_bound:  -8597.625
Upper_bound:  16445.375

In [102]:
len(products_cost_price_outlier)

129

In [103]:
products_cost_price_outlier.head()

,product_id,product_name,category,subcategory,brand,sku,mrp,selling_price,cost_price,gst_rate,hsn_code,weight_grams,supplier_id,rating,review_count,is_active,launch_date
0,PRD0001,Usha Smartphone Elite,Electronics,Smartphone,Usha,SKU-ELE-00001,92028,78958,55738,18,1144,250,SUP0198,4.3,3655,1,2025-01-29
1,PRD0002,Gizmore Smartphone Premium,Electronics,Smartphone,Gizmore,SKU-ELE-00002,91470,65917,48052,18,2857,2000,SUP0140,3.6,2321,1,2024-05-17
2,PRD0003,Fire-Boltt Smartphone Max,Electronics,Smartphone,Fire-Boltt,SKU-ELE-00003,148029,118800,68913,18,2349,250,SUP0113,3.5,4412,1,2024-12-28
3,PRD0004,Godrej Smartphone Elite,Electronics,Smartphone,Godrej,SKU-ELE-00004,152903,113203,80055,18,8130,250,SUP0068,4.5,1264,1,2023-05-04
5,PRD0006,Orient Smartphone Base,Electronics,Smartphone,Orient,SKU-ELE-00006,41611,33013,16882,18,2189,1500,SUP0029,4.8,874,1,2025-04-28

Cost Price Outlier: The IQR method identified 129 potential outliers above the upper bound of ₹16,445. These values were reviewed against related pricing fields to determine whether they represented genuine high-cost products or data-quality issues. Genuine high-value observations were retained rather than removed.

In [107]:
Q1 = products['weight_grams'].quantile(0.25)
Q3 = products['weight_grams'].quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

products_weight_grams_outlier = products[(products['weight_grams'] < lower) | 
    (products['weight_grams'] > upper)]

print('Q1: ',Q1)
print('Q3: ',Q3)
print('IQR: ',IQR)
print('Lower_bound: ',lower)
print('Upper_bound: ',upper)

Q1:  500.0
Q3:  2000.0
IQR:  1500.0
Lower_bound:  -1750.0
Upper_bound:  4250.0

In [108]:
len(products_weight_grams_outlier)

103

In [109]:
products_weight_grams_outlier.head()

,product_id,product_name,category,subcategory,brand,sku,mrp,selling_price,cost_price,gst_rate,hsn_code,weight_grams,supplier_id,rating,review_count,is_active,launch_date
24,PRD0025,Mahindra Tablet Plus,Electronics,Tablet,Mahindra,SKU-ELE-00025,176779,141311,87691,18,3135,5000,SUP0047,4.6,3539,1,2023-07-22
26,PRD0027,Crossbeats Tablet Pro,Electronics,Tablet,Crossbeats,SKU-ELE-00027,128476,109124,70330,18,2930,5000,SUP0001,3.2,1687,1,2023-04-01
31,PRD0032,Ambrane Smart TV Classic,Electronics,Smart TV,Ambrane,SKU-ELE-00032,23610,17063,10404,18,4304,5000,SUP0057,3.7,280,1,2024-05-04
34,PRD0035,Finolex Smart TV Elite,Electronics,Smart TV,Finolex,SKU-ELE-00035,3793,3219,1695,18,2185,5000,SUP0173,3.7,963,1,2022-12-03
50,PRD0051,Pidilite Bluetooth Speaker Plus,Electronics,Bluetooth Speaker,Pidilite,SKU-ELE-00051,26738,22988,12043,18,8752,5000,SUP0157,3.3,3257,1,2021-12-11

In [113]:
products_weight_grams_outlier[['product_id', 'product_name', 'category', 'weight_grams']].sort_values(
    by='weight_grams',
    ascending=False
)

    product_id                     product_name         category  weight_grams
24     PRD0025             Mahindra Tablet Plus      Electronics          5000
26     PRD0027            Crossbeats Tablet Pro      Electronics          5000
31     PRD0032         Ambrane Smart TV Classic      Electronics          5000
34     PRD0035           Finolex Smart TV Elite      Electronics          5000
50     PRD0051  Pidilite Bluetooth Speaker Plus      Electronics          5000
..         ...                              ...              ...           ...
979    PRD0980         Finolex Office Chair Pro  Office Supplies          5000
984    PRD0985            Ambrane Desk Lamp Pro  Office Supplies          5000
989    PRD0990           Infosys Desk Lamp Lite  Office Supplies          5000
997    PRD0998                HCL Pen Drive Pro  Office Supplies          5000
999    PRD1000      Mahindra Pen Drive Standard  Office Supplies          5000

[103 rows x 4 columns]

In [112]:
(products['weight_grams'] == 5000).sum()

np.int64(103)

Weight Grams Outlier: The IQR method identified potential outliers above the upper bound of 4,250 grams. During verification, 103 products were found with an identical weight of 5,000 grams across different product types and categories. This repeated value indicates a potential data-quality issue in the weight data.

In [114]:
Q1 = products['review_count'].quantile(0.25)
Q3 = products['review_count'].quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

products_review_count_outlier = products[(products['review_count'] < lower) | 
    (products['review_count'] > upper)]

print('Q1: ',Q1)
print('Q3: ',Q3)
print('IQR: ',IQR)
print('Lower_bound: ',lower)
print('Upper_bound: ',upper)

Q1:  1194.5
Q3:  3700.75
IQR:  2506.25
Lower_bound:  -2564.875
Upper_bound:  7460.125

In [115]:
len(products_review_count_outlier)

0

In [128]:
products.duplicated().sum()

np.int64(0)

In [83]:
# Returns table
returns.head()

,return_id,order_id,customer_id,return_date,reason,return_amount,refund_status,refund_date,return_condition,remarks
0,RET00001,ORD000015,CUST05470,23-12-2024,Size Issue,24167.33,Pending,30-12-2024,Damaged,Customer initiated return within 7 day window
1,RET00002,ORD000017,CUST07581,01-11-2023,Defective Product,11698.27,Refunded,06-11-2023,Damaged,Customer initiated return within 7 day window
2,RET00003,ORD000038,CUST05691,01-05-2025,Wrong Product Delivered,11147.74,Refunded,06-05-2025,Damaged,Customer initiated return within 7 day window
3,RET00004,ORD000054,CUST03170,20-06-2025,Duplicate Order,9284.55,Refunded,24-06-2025,Acceptable,Customer initiated return within 7 day window
4,RET00005,ORD000072,CUST09318,16-03-2025,Duplicate Order,36912.59,Refunded,23-03-2025,Good,Customer initiated return within 7 day window

In [116]:
returns.isnull().sum()

return_id           0
order_id            0
customer_id         0
return_date         0
reason              0
return_amount       0
refund_status       0
refund_date         0
return_condition    0
remarks             0
dtype: int64

In [117]:
returns.dtypes

return_id               str
order_id                str
customer_id             str
return_date             str
reason                  str
return_amount       float64
refund_status           str
refund_date             str
return_condition        str
remarks                 str
dtype: object

In [118]:
returns['return_date'] = pd.to_datetime(returns['return_date'], format = '%d-%m-%Y')

In [119]:
returns['refund_date'] = pd.to_datetime(returns['refund_date'], format = '%d-%m-%Y')

In [89]:
returns.dtypes

return_id                      str
order_id                       str
customer_id                    str
return_date         datetime64[us]
reason                         str
return_amount              float64
refund_status                  str
refund_date         datetime64[us]
return_condition               str
remarks                        str
dtype: object

In [120]:
returns.duplicated().sum()

np.int64(0)

In [121]:
Q1 = returns['return_amount'].quantile(0.25)
Q3 = returns['return_amount'].quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

returns_shipping_charge_outlier = returns[(returns['return_amount'] < lower) | 
    (returns['return_amount'] > upper)]

print('Q1: ',Q1)
print('Q3: ',Q3)
print('IQR: ',IQR)
print('Lower_bound: ',lower)
print('Upper_bound: ',upper)

Q1:  7364.61
Q3:  73126.7
IQR:  65762.09
Lower_bound:  -91278.525
Upper_bound:  171769.835

In [122]:
len(returns_shipping_charge_outlier)

1045

In [123]:
returns_shipping_charge_outlier.head()

,return_id,order_id,customer_id,return_date,reason,return_amount,refund_status,refund_date,return_condition,remarks
8,RET00009,ORD000111,CUST08499,2025-03-31,Defective Product,253986.78,Refunded,2025-04-06,Good,Customer initiated return within 7 day window
30,RET00031,ORD000340,CUST06514,2024-08-30,Not as Described,294567.12,Refunded,2024-09-03,Good,Customer initiated return within 7 day window
31,RET00032,ORD000348,CUST02794,2023-08-04,Damaged in Transit,396896.57,Refunded,2023-08-07,Acceptable,Customer initiated return within 7 day window
32,RET00033,ORD000358,CUST05540,2023-11-20,Not as Described,263508.88,Refunded,2023-11-26,Damaged,Customer initiated return within 7 day window
46,RET00047,ORD000531,CUST09163,2023-07-25,Duplicate Order,296544.02,Refunded,2023-08-01,Good,Customer initiated return within 7 day window

In [130]:
returns_shipping_charge_outlier[
    ['order_id', 'return_amount']
].sort_values(
    by='return_amount',
    ascending=False
)

       order_id  return_amount
2165  ORD027603     1133382.48
7596  ORD015470      892302.73
1539  ORD019554      885092.35
1680  ORD021474      817893.92
101   ORD001502      755160.93
...         ...            ...
6280  ORD006030      172703.23
4247  ORD002527      172295.44
8328  ORD005385      172061.53
5201  ORD007001      171937.99
7177  ORD014120      171791.02

[1045 rows x 2 columns]

Return Amount Outlier: The IQR method identified 1,045 potential outliers above the upper bound of ₹171,761. The identified values range from approximately ₹171,791 to ₹11.33 lakh, indicating a substantial number of unusually high return amounts compared with the majority of records.

In [127]:
returns.duplicated().sum()

np.int64(0)

In [91]:
# Suppliers table
suppliers.head()

,supplier_id,supplier_name,contact_person,email,phone,city,state,pincode,category,gstin,payment_terms_days,rating,created_date,is_active
0,SUP0001,Iyer Elec Pvt Ltd,Harish Iyer,contact@iyerele.com,9362950628,Delhi,Delhi,334053,Electronics,14TRXCK1488C4Z9,15,4.1,22-05-2023,1
1,SUP0002,Sharma Offi Pvt Ltd,Mohit Sharma,contact@sharmaoff.com,9914763202,Ahmedabad,Gujarat,267414,Office Supplies,32KHFTC7224C6Z5,15,4.5,25-03-2023,1
2,SUP0003,Choudhury Beau Pvt Ltd,Nandini Choudhury,contact@choudhurybea.com,9764130526,Pune,Maharashtra,479201,Beauty & Health,28EBRUZ4814W7Z5,60,4.3,27-12-2022,1
3,SUP0004,Choudhury Fash Pvt Ltd,Vikram Choudhury,contact@choudhuryfas.com,9283758720,Chennai,Tamil Nadu,660086,Fashion,33GMHYR4598R1Z4,15,4.6,15-01-2023,1
4,SUP0005,Patil Spor Pvt Ltd,Kiran Patil,contact@patilspo.com,9636045484,Jaipur,Rajasthan,514850,Sports & Fitness,30LGGOG8019X7Z6,30,5.0,02-09-2022,1

In [124]:
suppliers.isnull().sum()

supplier_id           0
supplier_name         0
contact_person        0
email                 0
phone                 0
city                  0
state                 0
pincode               0
category              0
gstin                 0
payment_terms_days    0
rating                0
created_date          0
is_active             0
dtype: int64

In [125]:
suppliers.dtypes

supplier_id               str
supplier_name             str
contact_person            str
email                     str
phone                   int64
city                      str
state                     str
pincode                 int64
category                  str
gstin                     str
payment_terms_days      int64
rating                float64
created_date              str
is_active               int64
dtype: object

In [29]:
suppliers['created_date'] = pd.to_datetime(suppliers['created_date'], format = '%d-%m-%Y')

In [95]:
suppliers.dtypes

supplier_id                      str
supplier_name                    str
contact_person                   str
email                            str
phone                          int64
city                             str
state                            str
pincode                        int64
category                         str
gstin                            str
payment_terms_days             int64
rating                       float64
created_date          datetime64[us]
is_active                      int64
dtype: object

In [126]:
suppliers.duplicated().sum()

np.int64(0)

In [134]:
Q1 = suppliers['payment_terms_days'].quantile(0.25)
Q3 = suppliers['payment_terms_days'].quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

suppliers_payment_terms_days_outlier = suppliers[(suppliers['payment_terms_days'] < lower) | 
    (suppliers['payment_terms_days'] > upper)]

print('Q1: ',Q1)
print('Q3: ',Q3)
print('IQR: ',IQR)
print('Lower_bound: ',lower)
print('Upper_bound: ',upper)

Q1:  15.0
Q3:  60.0
IQR:  45.0
Lower_bound:  -52.5
Upper_bound:  127.5

In [135]:
len(suppliers_payment_terms_days_outlier)

0

Specific checks:

In [42]:
(orders['final_amount'] > 500000).sum()

np.int64(312)

In [44]:
orders['amount_flag'] = orders['final_amount'] > 500000

0        False
1        False
2        False
3        False
4        False
         ...
49995    False
49996    False
49997    False
49998    False
49999    False
Name: amount_flag, Length: 50000, dtype: bool

In [46]:
orders

,order_id,customer_id,order_date,order_time,status,city,state,pincode,total_amount,gst_amount,shipping_charge,discount_amount,final_amount,payment_method,shipping_partner,tracking_id,delivered_date,is_cod,channel,amount_flag
0,ORD000001,CUST02946,22-05-2025,17:10:00,Processing,Pune,Maharashtra,300862,100984.19,16364.64,0,20486.45,100984.19,Cash on Delivery,BlueDart,TRK354572763,NaN,1,App,False
1,ORD000002,CUST04232,16-10-2023,05:32:00,Delivered,Ludhiana,Punjab,387852,254478.01,41599.80,0,19338.79,254478.01,UPI,DTDC,TRK272838570,19-10-2023,0,Website,False
2,ORD000003,CUST08078,08-10-2023,12:32:00,Cancelled,Meerut,Uttar Pradesh,294014,32557.06,3562.92,0,696.86,32557.06,Debit Card,Amazon Logistics,TRK338505401,NaN,0,App,False
3,ORD000004,CUST09612,02-10-2023,08:05:00,Delivered,Nashik,Maharashtra,626047,24836.94,3092.88,0,4029.94,24836.94,UPI,DTDC,TRK289792017,09-10-2023,0,Mobile Web,False
4,ORD000005,CUST03065,15-06-2024,20:19:00,Delivered,Moradabad,Uttar Pradesh,409210,156689.29,25092.36,0,7805.07,156689.29,UPI,Ecom Express,TRK978240041,22-06-2024,0,App,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49995,ORD049996,CUST06694,30-11-2023,02:02:00,Returned,Varanasi,Uttar Pradesh,211491,2922.08,745.36,0,485.28,2922.08,Credit Card,Delhivery,TRK377660669,NaN,0,Mobile Web,False
49996,ORD049997,CUST01649,29-03-2025,01:04:00,Cancelled,Nagpur,Maharashtra,475562,1844.05,312.48,0,689.71,1844.05,UPI,DTDC,TRK973715414,NaN,0,App,False
49997,ORD049998,CUST03865,14-12-2024,00:35:00,Delivered,Pune,Maharashtra,132579,13023.59,1452.96,0,1647.00,13023.59,Debit Card,Ecom Express,TRK187824914,18-12-2024,0,App,False
49998,ORD049999,CUST04997,02-01-2025,22:57:00,Shipped,Varanasi,Uttar Pradesh,782507,25068.84,4137.84,0,2057.00,25068.84,Credit Card,BlueDart,TRK205502040,NaN,0,Website,False
49999,ORD050000,CUST03422,10-05-2024,00:14:00,Processing,Raipur,Chhattisgarh,406380,1861.38,235.32,0,334.94,1861.38,Cash on Delivery,Amazon Logistics,TRK253765683,NaN,1,Website,False

In [49]:
order_items[~order_items['order_id'].isin(orders['order_id'])]

Empty DataFrame
Columns: [item_id, order_id, product_id, product_name, category, quantity, unit_price, gst_rate, gst_amount, discount_amount, total_price]
Index: []

In [50]:
(~order_items['order_id'].isin(orders['order_id'])).sum()

np.int64(0)

In [62]:
orders['flag_dates'] = (orders['delivered_date'].notna() & 
                        (orders['delivered_date'] <= orders['order_date'])
                       )

In [63]:
orders['flag_dates'].sum()

np.int64(0)

In [64]:
payments['status'].value_counts()

status
Success    48252
Failed      1748
Name: count, dtype: int64

In [65]:
payments['status'].value_counts(normalize=True) * 100

status
Success    96.504
Failed      3.496
Name: proportion, dtype: float64

In [66]:
returns[~returns['order_id'].isin(orders['order_id'])]

Empty DataFrame
Columns: [return_id, order_id, customer_id, return_date, reason, return_amount, refund_status, refund_date, return_condition, remarks]
Index: []

In [70]:
inventory['status'].value_counts()

status
In Stock        922
Low Stock        76
Out of Stock      2
Name: count, dtype: int64

In [73]:
(inventory['status'] == 'Out of Stock').sum()

np.int64(2)

In [75]:
customers.head()

,customer_id,first_name,last_name,email,phone,city,state,pincode,gender,age,segment,registration_date,last_login_date,is_verified,is_active,total_orders,total_spent
0,CUST00001,Kunal,Gupta,kunal.gupta223@gmail.com,9117912889,Guwahati,Assam,314040,Male,54,New,2024-07-30,2025-04-10,0,1,7,1028341.51
1,CUST00002,Aryan,Gupta,aryan.gupta336@yahoo.in,9271550550,Navi Mumbai,Maharashtra,799535,Female,26,Budget,2023-07-05,2024-05-03,1,1,1,20337.39
2,CUST00003,Akash,Chatterjee,akash.chatterjee584@hotmail.com,9559676548,Surat,Gujarat,738196,Female,24,Regular,2022-05-14,2023-10-31,1,1,7,265688.26
3,CUST00004,Madhuri,Walia,madhuri.walia878@gmail.com,9673322422,Gwalior,Madhya Pradesh,238106,Female,23,Regular,2025-01-21,2025-05-22,1,0,7,173446.94
4,CUST00005,Vishal,Das,vishal.das342@yahoo.in,9920855521,Dhanbad,Jharkhand,783291,Female,59,Regular,2023-06-06,2024-03-29,1,0,4,239808.60

In [76]:
customers[customers['total_orders'] == 0]

,customer_id,first_name,last_name,email,phone,city,state,pincode,gender,age,segment,registration_date,last_login_date,is_verified,is_active,total_orders,total_spent
65,CUST00066,Geeta,Mehta,geeta.mehta895@gmail.com,9652228587,Moradabad,Uttar Pradesh,389882,Male,44,New,2022-04-10,2023-03-02,1,1,0,0.0
121,CUST00122,Ravi,Ghosh,ravi.ghosh911@gmail.com,9334559782,Madurai,Tamil Nadu,444600,Male,25,Inactive,2020-08-15,2020-10-21,1,1,0,0.0
123,CUST00124,Ashish,Pandey,ashish.pandey103@gmail.com,9986400277,Navi Mumbai,Maharashtra,690717,Female,62,Inactive,2022-01-05,2023-07-02,1,1,0,0.0
127,CUST00128,Sanjay,Dwivedi,sanjay.dwivedi962@yahoo.in,9683627205,Solapur,Maharashtra,500721,Male,38,Inactive,2021-01-06,2025-06-07,0,0,0,0.0
161,CUST00162,Ashish,Ghosh,ashish.ghosh439@gmail.com,9470012350,Kolkata,West Bengal,285383,Female,59,Inactive,2022-11-17,2025-05-23,1,1,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9936,CUST09937,Meera,Walia,meera.walia625@yahoo.in,9733401858,Nashik,Maharashtra,224555,Female,22,Inactive,2021-09-18,2023-08-13,0,1,0,0.0
9937,CUST09938,Deepak,Kumar,deepak.kumar695@gmail.com,9143324547,Ahmedabad,Gujarat,733056,Male,45,Budget,2021-11-09,2025-03-03,1,1,0,0.0
9960,CUST09961,Kavya,Mukherjee,kavya.mukherjee875@gmail.com,9102503645,Jabalpur,Madhya Pradesh,618665,Male,43,Budget,2024-07-21,2024-12-24,0,1,0,0.0
9985,CUST09986,Akash,Roy,akash.roy507@gmail.com,9690805934,Ranchi,Jharkhand,613292,Female,41,Inactive,2021-07-21,2022-03-04,1,1,0,0.0
9997,CUST09998,Rahul,Gandhi,rahul.gandhi890@yahoo.in,9585241749,Vadodara,Gujarat,408872,Male,38,Budget,2020-11-27,2022-06-20,1,1,0,0.0

In [77]:
(customers['total_orders'] == 0).sum()

np.int64(457)

IndiaCart E-Commerce Analytics
Phase 1: Data Cleaning Summary
Objective

The objective of Phase 1 was to inspect and clean the IndiaCart e-commerce datasets to improve data quality and prepare the data for Exploratory Data Analysis (EDA), KPI analysis, and dashboard development.

Data Quality Checks Performed

The datasets were loaded into Python and systematically checked for:

Missing/null values
Incorrect data types
Duplicate records
Statistical outliers in relevant numerical columns
Invalid or unusual values
Cleaning & Validation Summary

Missing Values:
The datasets were checked for missing/null values using Python. Columns containing missing values were identified and reviewed before analysis.

Data Types:
Data types were inspected using info() and relevant columns were checked to ensure that numerical, categorical, and date fields were represented appropriately for analysis.

Duplicate Records:
Duplicate records were checked using duplicated(). Duplicate records, where identified, were handled to prevent them from affecting analysis and reporting.

Outlier Detection:
The IQR method was applied only to meaningful numerical/continuous variables rather than identifiers or code fields.

Key findings included:

Product Cost Price: 129 potential outliers were identified above the upper bound of 16,445.

Product Weight: Potential outliers were identified above the upper bound of 4,250 grams. During verification, 103 products had a repeated weight of 5,000 grams across different product types/categories, indicating a potential data-quality issue.

Return Amount: 1,045 potential outliers were identified above the upper bound of 171,769 The identified values ranged from approximately 171,791 to 1.13 million.

Supplier Payment Terms: This numerical field was considered appropriate for outlier analysis, while fields such as phone numbers, PIN codes, and IDs were excluded because they are identifiers/codes rather than measurable quantities.

Customer Age: The IQR check did not identify outliers requiring treatment.
Result

The cleaned and validated datasets are now prepared for the next phases of the IndiaCart project. The cleaning process focused on identifying data-quality issues while avoiding unnecessary removal of legitimate business values. The resulting data will be used for EDA, KPI calculation, Power BI dashboard development, and management insights.

In [136]:
customers.to_csv("../Cleaned Data/customers_cleaned.csv", index=False)

In [137]:
inventory.to_csv('../Cleaned Data/inventory_cleaned.csv', index=False)

In [138]:
order_items.to_csv('../Cleaned Data/order_items_cleaned.csv', index=False)

In [139]:
orders.to_csv('../Cleaned Data/orders_cleaned.csv', index=False)

In [140]:
payments.to_csv('../Cleaned Data/payments_cleaned.csv', index=False)

In [141]:
products.to_csv('../Cleaned Data/products_cleaned.csv', index=False)

In [142]:
returns.to_csv('../Cleaned Data/returns_cleaned.csv', index=False)

In [143]:
suppliers.to_csv('../Cleaned Data/suppliers_cleaned.csv', index=False)